### PR TITLE
Auto-update feeds every hour

### PR DESCRIPTION
**Pull request by antstorm**
Hey,

Here's a little PR that enables optional auto-updating of the feeds every hour. It's off by default.

### CODE REVIEW

**Comment by goddamnyouryan** [comment]
What is the use-case for this? If you have a tab open for more than an hour, it will bring in the new posts? I can't imagine that is a huge usecase. I also believe that the backend runs every 10 minutes so it seems  strange to only auto-update once an hour.

Are you using this by visiting coven.link or do you have the chrome empty tab plugin? I'd recommend using the latter if you aren't already, it should solve any issues you're having with wanting it to auto-update.

**Comment by antstorm** [comment]
Yeah, you're right, the way I use it is I have a pinned tab open which I check every now and then whenever I got some spare time. So with this change I will have new posts available when I open it. I used the 1 hour interval, because it seems more than enough for news reading. By all means I can reduce it or make it adjustable (although it feels like an overkill).

I haven't switched to the empty tab plugin because it's too much distraction whenever I open a new tab, which I prefer to keep empty.

**Comment by goddamnyouryan** [comment]
cool! I can appreciate that! Merging and deploying now.

**Comment by antstorm** [comment]
Great, thanks!

**Pull request merged**
